==56852== Memcheck, a memory error detector
==56852== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==56852== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==56852== Command: ./test
==56852== 
==56852== 
==56852== HEAP SUMMARY:
==56852==     in use at exit: 28 bytes in 7 blocks
==56852==   total heap usage: 8,084 allocs, 8,077 frees, 787,923 bytes allocated
==56852== 
==56852== 4 bytes in 1 blocks are definitely lost in loss record 1 of 7
==56852==    at 0x483BE63: operator new(unsigned long) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==56852==    by 0x1214C8: string_map<int>::insert(std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int> const&) (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/1377_21/taller3/correcciones/2022-11-24/test)
==56852==    by 0x11E433: string_map_test_eraseUnicaClave_Test::TestBody() (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/1377_21/taller3/correcciones/2022-11-24/test)
==56852==    by 0x154110: HandleSehExceptionsInMethodIfSupported<testing::Test, void> (gtest.cc:2433)
==56852==    by 0x154110: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2469)
==56852==    by 0x147465: Run (gtest.cc:2508)
==56852==    by 0x147465: testing::Test::Run() (gtest.cc:2498)
==56852==    by 0x1475C4: Run (gtest.cc:2684)
==56852==    by 0x1475C4: testing::TestInfo::Run() (gtest.cc:2657)
==56852==    by 0x1476AC: Run (gtest.cc:2816)
==56852==    by 0x1476AC: testing::TestSuite::Run() (gtest.cc:2795)
==56852==    by 0x147BCB: testing::internal::UnitTestImpl::RunAllTests() (gtest.cc:5338)
==56852==    by 0x154680: HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (gtest.cc:2433)
==56852==    by 0x154680: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2469)
==56852==    by 0x147DFB: testing::UnitTest::Run() (gtest.cc:4925)
==56852==    by 0x120A5B: RUN_ALL_TESTS() (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/1377_21/taller3/correcciones/2022-11-24/test)
==56852==    by 0x11FDA9: main (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/1377_21/taller3/correcciones/2022-11-24/test)
==56852== 
==56852== 4 bytes in 1 blocks are definitely lost in loss record 2 of 7
==56852==    at 0x483BE63: operator new(unsigned long) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==56852==    by 0x1214C8: string_map<int>::insert(std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int> const&) (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/1377_21/taller3/correcciones/2022-11-24/test)
==56852==    by 0x11E8F5: string_map_test_erase_Test::TestBody() (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/1377_21/taller3/correcciones/2022-11-24/test)
==56852==    by 0x154110: HandleSehExceptionsInMethodIfSupported<testing::Test, void> (gtest.cc:2433)
==56852==    by 0x154110: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2469)
==56852==    by 0x147465: Run (gtest.cc:2508)
==56852==    by 0x147465: testing::Test::Run() (gtest.cc:2498)
==56852==    by 0x1475C4: Run (gtest.cc:2684)
==56852==    by 0x1475C4: testing::TestInfo::Run() (gtest.cc:2657)
==56852==    by 0x1476AC: Run (gtest.cc:2816)
==56852==    by 0x1476AC: testing::TestSuite::Run() (gtest.cc:2795)
==56852==    by 0x147BCB: testing::internal::UnitTestImpl::RunAllTests() (gtest.cc:5338)
==56852==    by 0x154680: HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (gtest.cc:2433)
==56852==    by 0x154680: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2469)
==56852==    by 0x147DFB: testing::UnitTest::Run() (gtest.cc:4925)
==56852==    by 0x120A5B: RUN_ALL_TESTS() (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/1377_21/taller3/correcciones/2022-11-24/test)
==56852==    by 0x11FDA9: main (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/1377_21/taller3/correcciones/2022-11-24/test)
==56852== 
==56852== 4 bytes in 1 blocks are definitely lost in loss record 3 of 7
==56852==    at 0x483BE63: operator new(unsigned long) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==56852==    by 0x1214C8: string_map<int>::insert(std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int> const&) (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/1377_21/taller3/correcciones/2022-11-24/test)
==56852==    by 0x11E949: string_map_test_erase_Test::TestBody() (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/1377_21/taller3/correcciones/2022-11-24/test)
==56852==    by 0x154110: HandleSehExceptionsInMethodIfSupported<testing::Test, void> (gtest.cc:2433)
==56852==    by 0x154110: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2469)
==56852==    by 0x147465: Run (gtest.cc:2508)
==56852==    by 0x147465: testing::Test::Run() (gtest.cc:2498)
==56852==    by 0x1475C4: Run (gtest.cc:2684)
==56852==    by 0x1475C4: testing::TestInfo::Run() (gtest.cc:2657)
==56852==    by 0x1476AC: Run (gtest.cc:2816)
==56852==    by 0x1476AC: testing::TestSuite::Run() (gtest.cc:2795)
==56852==    by 0x147BCB: testing::internal::UnitTestImpl::RunAllTests() (gtest.cc:5338)
==56852==    by 0x154680: HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (gtest.cc:2433)
==56852==    by 0x154680: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2469)
==56852==    by 0x147DFB: testing::UnitTest::Run() (gtest.cc:4925)
==56852==    by 0x120A5B: RUN_ALL_TESTS() (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/1377_21/taller3/correcciones/2022-11-24/test)
==56852==    by 0x11FDA9: main (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/1377_21/taller3/correcciones/2022-11-24/test)
==56852== 
==56852== 4 bytes in 1 blocks are definitely lost in loss record 4 of 7
==56852==    at 0x483BE63: operator new(unsigned long) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==56852==    by 0x1214C8: string_map<int>::insert(std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int> const&) (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/1377_21/taller3/correcciones/2022-11-24/test)
==56852==    by 0x11E99D: string_map_test_erase_Test::TestBody() (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/1377_21/taller3/correcciones/2022-11-24/test)
==56852==    by 0x154110: HandleSehExceptionsInMethodIfSupported<testing::Test, void> (gtest.cc:2433)
==56852==    by 0x154110: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2469)
==56852==    by 0x147465: Run (gtest.cc:2508)
==56852==    by 0x147465: testing::Test::Run() (gtest.cc:2498)
==56852==    by 0x1475C4: Run (gtest.cc:2684)
==56852==    by 0x1475C4: testing::TestInfo::Run() (gtest.cc:2657)
==56852==    by 0x1476AC: Run (gtest.cc:2816)
==56852==    by 0x1476AC: testing::TestSuite::Run() (gtest.cc:2795)
==56852==    by 0x147BCB: testing::internal::UnitTestImpl::RunAllTests() (gtest.cc:5338)
==56852==    by 0x154680: HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (gtest.cc:2433)
==56852==    by 0x154680: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2469)
==56852==    by 0x147DFB: testing::UnitTest::Run() (gtest.cc:4925)
==56852==    by 0x120A5B: RUN_ALL_TESTS() (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/1377_21/taller3/correcciones/2022-11-24/test)
==56852==    by 0x11FDA9: main (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/1377_21/taller3/correcciones/2022-11-24/test)
==56852== 
==56852== 4 bytes in 1 blocks are definitely lost in loss record 5 of 7
==56852==    at 0x483BE63: operator new(unsigned long) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==56852==    by 0x1214C8: string_map<int>::insert(std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int> const&) (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/1377_21/taller3/correcciones/2022-11-24/test)
==56852==    by 0x11E9F1: string_map_test_erase_Test::TestBody() (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/1377_21/taller3/correcciones/2022-11-24/test)
==56852==    by 0x154110: HandleSehExceptionsInMethodIfSupported<testing::Test, void> (gtest.cc:2433)
==56852==    by 0x154110: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2469)
==56852==    by 0x147465: Run (gtest.cc:2508)
==56852==    by 0x147465: testing::Test::Run() (gtest.cc:2498)
==56852==    by 0x1475C4: Run (gtest.cc:2684)
==56852==    by 0x1475C4: testing::TestInfo::Run() (gtest.cc:2657)
==56852==    by 0x1476AC: Run (gtest.cc:2816)
==56852==    by 0x1476AC: testing::TestSuite::Run() (gtest.cc:2795)
==56852==    by 0x147BCB: testing::internal::UnitTestImpl::RunAllTests() (gtest.cc:5338)
==56852==    by 0x154680: HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (gtest.cc:2433)
==56852==    by 0x154680: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2469)
==56852==    by 0x147DFB: testing::UnitTest::Run() (gtest.cc:4925)
==56852==    by 0x120A5B: RUN_ALL_TESTS() (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/1377_21/taller3/correcciones/2022-11-24/test)
==56852==    by 0x11FDA9: main (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/1377_21/taller3/correcciones/2022-11-24/test)
==56852== 
==56852== 4 bytes in 1 blocks are definitely lost in loss record 6 of 7
==56852==    at 0x483BE63: operator new(unsigned long) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==56852==    by 0x1214C8: string_map<int>::insert(std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int> const&) (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/1377_21/taller3/correcciones/2022-11-24/test)
==56852==    by 0x11EA45: string_map_test_erase_Test::TestBody() (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/1377_21/taller3/correcciones/2022-11-24/test)
==56852==    by 0x154110: HandleSehExceptionsInMethodIfSupported<testing::Test, void> (gtest.cc:2433)
==56852==    by 0x154110: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2469)
==56852==    by 0x147465: Run (gtest.cc:2508)
==56852==    by 0x147465: testing::Test::Run() (gtest.cc:2498)
==56852==    by 0x1475C4: Run (gtest.cc:2684)
==56852==    by 0x1475C4: testing::TestInfo::Run() (gtest.cc:2657)
==56852==    by 0x1476AC: Run (gtest.cc:2816)
==56852==    by 0x1476AC: testing::TestSuite::Run() (gtest.cc:2795)
==56852==    by 0x147BCB: testing::internal::UnitTestImpl::RunAllTests() (gtest.cc:5338)
==56852==    by 0x154680: HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (gtest.cc:2433)
==56852==    by 0x154680: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2469)
==56852==    by 0x147DFB: testing::UnitTest::Run() (gtest.cc:4925)
==56852==    by 0x120A5B: RUN_ALL_TESTS() (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/1377_21/taller3/correcciones/2022-11-24/test)
==56852==    by 0x11FDA9: main (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/1377_21/taller3/correcciones/2022-11-24/test)
==56852== 
==56852== 4 bytes in 1 blocks are definitely lost in loss record 7 of 7
==56852==    at 0x483BE63: operator new(unsigned long) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==56852==    by 0x1214C8: string_map<int>::insert(std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int> const&) (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/1377_21/taller3/correcciones/2022-11-24/test)
==56852==    by 0x11EA99: string_map_test_erase_Test::TestBody() (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/1377_21/taller3/correcciones/2022-11-24/test)
==56852==    by 0x154110: HandleSehExceptionsInMethodIfSupported<testing::Test, void> (gtest.cc:2433)
==56852==    by 0x154110: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2469)
==56852==    by 0x147465: Run (gtest.cc:2508)
==56852==    by 0x147465: testing::Test::Run() (gtest.cc:2498)
==56852==    by 0x1475C4: Run (gtest.cc:2684)
==56852==    by 0x1475C4: testing::TestInfo::Run() (gtest.cc:2657)
==56852==    by 0x1476AC: Run (gtest.cc:2816)
==56852==    by 0x1476AC: testing::TestSuite::Run() (gtest.cc:2795)
==56852==    by 0x147BCB: testing::internal::UnitTestImpl::RunAllTests() (gtest.cc:5338)
==56852==    by 0x154680: HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (gtest.cc:2433)
==56852==    by 0x154680: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2469)
==56852==    by 0x147DFB: testing::UnitTest::Run() (gtest.cc:4925)
==56852==    by 0x120A5B: RUN_ALL_TESTS() (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/1377_21/taller3/correcciones/2022-11-24/test)
==56852==    by 0x11FDA9: main (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/1377_21/taller3/correcciones/2022-11-24/test)
==56852== 
==56852== LEAK SUMMARY:
==56852==    definitely lost: 28 bytes in 7 blocks
==56852==    indirectly lost: 0 bytes in 0 blocks
==56852==      possibly lost: 0 bytes in 0 blocks
==56852==    still reachable: 0 bytes in 0 blocks
==56852==         suppressed: 0 bytes in 0 blocks
==56852== 
==56852== For lists of detected and suppressed errors, rerun with: -s
==56852== ERROR SUMMARY: 7 errors from 7 contexts (suppressed: 0 from 0)
